---
- hosts: all
  vars:
         ansible_python_interpreter: "/usr/bin/python3"
 
  tasks:
    - name: Login
      shell: sudo docker login
    
    - name: Start service
      shell: sudo docker-compose -f /tmp/docker-compose.yml up -d